### ISSUE TITLE
Please Help me solve this

### ISSUE THREAD

**Issue by LaxmanMaharjan** [canovasjm/covid-19-san-juan#1]
This is python file
import smtplib
import os
from email.message import EmailMessage

EMAIL_ADDRESS = os.environ.get('EMAIL_ADDRESS')
EMAIL_PASSWORD = os.environ.get('EMAIL_PASSWORD')

msg = EmailMessage()
msg['Subject'] = 'Checking smtplib FROM GITHUB'
msg['From'] = EMAIL_ADDRESS
msg['To'] = 'lxmnmrzn@gmail.com'

msg.set_content('This is a email check.')

with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
    smtp.login(EMAIL_ADDRESS, EMAIL_PASSWORD)
    smtp.send_message(msg)
    
This is .yml file
name: CI

on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '*/5 * * * *'

  workflow_dispatch:

jobs:
 
  build:
 
    runs-on: ubuntu-latest

    steps:
   
      - uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          
      - name: execute py script 
        env: 
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
       
        run: python send_email.py

This error comes while running python file in github actions
 TypeError: can only concatenate str (not "bytes") to str

**Comment by canovasjm** [comment]
Apparently, the .yml workflow is running correctly and the error seems to be in the python code. Have you properly set up the GitHub secrets `EMAIL_ADDRESS` and `EMAIL_PASSWORD` ?

**Comment by LaxmanMaharjan** [comment]
I think I did it properly
Took Reference from your blog

**Comment by LaxmanMaharjan** [comment]
smtp.login(EMAIL_ADDRESS, EMAIL_PASSWORD)
TypeError: can only concatenate str (not "bytes") to str
I can't understand why this error appears even though EMAIL_ADDRESS and EMAIL_PASSWORD are both str type

**Comment by canovasjm** [comment]
I think there is still an issue with the GitHub secrets, from what I see in the log from your failed run. You can check it as follows:

1) Go to your repo
2) Go to the "Actions" tab
3) Select the failed run
4) Select "build" under jobs
5) Unfold "execute py script"
6) Unfold "Run python send email"
7) Check the secrets' name under `env:`

![image](https://user-images.githubusercontent.com/19241669/116001474-fe199b80-a5ca-11eb-8c2e-5ee4dd9b33d3.png)

The successful log for mi repository looks as follows: 

![image](https://user-images.githubusercontent.com/19241669/116001705-2950ba80-a5cc-11eb-85f8-92d252441ff2.png)

You can see mine has three stars `***` , indicating that something is being read there. This is not the case for your workflow.

**Comment by LaxmanMaharjan** [comment]
Yes Thank you so much
There was an issue with the GitHub secrets, was setting secrets in environment instead of repo.
Thank you for help means a lot.

**Comment by canovasjm** [comment]
I'm glad it helped! :)
